<#
.SYNOPSIS
    Bulk migration workflow: clone repos, create branches, scan, track status, send PRs.

.DESCRIPTION
    Automates the bulk migration of .NET repos in a GitHub org from Chat Completions
    to Responses API.

.EXAMPLE
    .\Invoke-BulkMigration.ps1 prepare -Org myorg
    .\Invoke-BulkMigration.ps1 status -WorkDir .\migrations
    .\Invoke-BulkMigration.ps1 send-prs -WorkDir .\migrations
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0, Mandatory)]
    [ValidateSet("prepare", "status", "send-prs")]
    [string]$SubCommand,

    [Parameter(Position = 1, ValueFromRemainingArguments)]
    [string[]]$Arguments
)

$ErrorActionPreference = "Stop"

$BranchName = "azure-openai-to-responses-api"
$PrTitle = "Migrate from Azure OpenAI Chat Completions to Responses API (.NET)"
$PrBody = @"
## What this PR does

Migrates this .NET app from Azure OpenAI SDK (``Azure.AI.OpenAI``) with Chat Completions to the OpenAI SDK (``OpenAI``) with Responses API.

### Changes
- ``AzureOpenAIClient`` / ``GetChatClient`` → ``ResponsesClient`` with ``OpenAIClientOptions``
- ``CompleteChatAsync(messages)`` → ``CreateResponseAsync(model, input, options)``
- ``response.Content[0].Text`` → ``response.GetOutputText()``
- NuGet: ``Azure.AI.OpenAI`` removed, ``OpenAI`` >= 2.9.1 added
- Test infrastructure updated (mocks, assertions)
- Removed ``api_version`` / ``AZURE_OPENAI_API_VERSION`` from config and infra

### Why
GPT-5 and newer models require the Responses API. The ``/openai/v1/`` endpoint is stable and requires no ``api_version`` management.

### How to verify
``````
dotnet build
dotnet test
``````

---
*Generated by [azure-openai-to-responses-csharp](https://github.com/Azure-Samples/azure-openai-to-responses-csharp)*
"@

$Root = Split-Path $PSScriptRoot -Parent
$Scanner = Join-Path $Root ".github" "skills" "azure-openai-to-responses-csharp" "scripts" "Detect-LegacyOpenAI.ps1"

function Parse-NamedArgs {
    param([string[]]$Args)
    $result = @{}
    for ($i = 0; $i -lt $Args.Count; $i++) {
        if ($Args[$i] -match '^-(\w+)$') {
            $name = $Matches[1]
            if ($i + 1 -lt $Args.Count -and -not $Args[$i + 1].StartsWith('-')) {
                $result[$name] = $Args[$i + 1]
                $i++
            }
            else {
                $result[$name] = $true
            }
        }
    }
    return $result
}

function Invoke-Prepare {
    param([string[]]$Args)
    $params = Parse-NamedArgs $Args

    $org = $params["Org"]
    if (-not $org) { Write-Error "Required: -Org <name>"; return 1 }

    $language = $params["Language"] ?? "csharp"
    $workDir = $params["WorkDir"] ?? ".\bulk-migrations"
    $workDir = (New-Item -ItemType Directory -Path $workDir -Force).FullName

    # Verify gh auth
    $username = gh api /user --jq ".login" 2>$null
    if (-not $username) { Write-Error "gh CLI not authenticated. Run 'gh auth login' first."; return 1 }
    Write-Host "Authenticated as: $username" -ForegroundColor Gray

    # Discover repos using Find-LegacyOpenAIRepos
    $findScript = Join-Path $PSScriptRoot "Find-LegacyOpenAIRepos.ps1"
    Write-Host "Discovering repos in '$org' with legacy patterns..." -ForegroundColor Cyan
    $jsonOutput = & $findScript -Org $org -Language $language -AsJson | Out-String
    $discoveryResult = $jsonOutput | ConvertFrom-Json

    if ($discoveryResult.total_repos -eq 0) {
        Write-Host "No repos found with legacy patterns." -ForegroundColor Green
        return 0
    }

    Write-Host "Found $($discoveryResult.total_repos) repo(s) with legacy patterns." -ForegroundColor Yellow
    Write-Host ""

    $manifest = @{}

    foreach ($repoInfo in $discoveryResult.repos) {
        $repoFull = $repoInfo.repo
        $repoShort = ($repoFull -split '/')[1]
        $repoDir = Join-Path $workDir $repoShort

        Write-Host "--- $repoFull ---" -ForegroundColor White

        # Clone
        if (-not (Test-Path $repoDir)) {
            Write-Host "  Cloning..." -ForegroundColor Gray
            gh repo clone $repoFull $repoDir -- --quiet 2>$null
        }
        else {
            Write-Host "  Already cloned." -ForegroundColor Gray
        }

        # Create branch
        Push-Location $repoDir
        try {
            $currentBranch = git branch --show-current 2>$null
            if ($currentBranch -ne $BranchName) {
                git checkout -b $BranchName 2>$null
            }
        }
        finally {
            Pop-Location
        }

        # Scan
        Write-Host "  Scanning..." -ForegroundColor Gray
        & $Scanner -Path $repoDir 2>$null | Out-Null
        $scanResult = $LASTEXITCODE

        $manifest[$repoShort] = @{
            full_name = $repoFull
            path      = $repoDir
            scan_hits = if ($scanResult -eq 0) { 0 } else { 1 }
            status    = if ($scanResult -eq 0) { "clean" } else { "needs-migration" }
        }

        Write-Host "  Status: $(if ($scanResult -eq 0) { 'clean' } else { 'needs migration' })" -ForegroundColor $(if ($scanResult -eq 0) { 'Green' } else { 'Yellow' })
        Write-Host ""
    }

    # Save manifest
    $manifestPath = Join-Path $workDir "manifest.json"
    $manifest | ConvertTo-Json -Depth 3 | Set-Content $manifestPath
    Write-Host "Manifest saved to $manifestPath" -ForegroundColor Cyan
    return 0
}

function Invoke-Status {
    param([string[]]$Args)
    $params = Parse-NamedArgs $Args
    $workDir = $params["WorkDir"] ?? ".\bulk-migrations"

    $manifestPath = Join-Path $workDir "manifest.json"
    if (-not (Test-Path $manifestPath)) {
        Write-Error "No manifest found at $manifestPath. Run 'prepare' first."
        return 1
    }

    $manifest = Get-Content $manifestPath | ConvertFrom-Json -AsHashtable

    Write-Host ""
    Write-Host "  Bulk Migration Status" -ForegroundColor Cyan
    Write-Host "  =====================" -ForegroundColor DarkGray
    Write-Host ""

    foreach ($repo in ($manifest.Keys | Sort-Object)) {
        $info = $manifest[$repo]
        $statusColor = switch ($info.status) {
            "clean"          { "Green" }
            "needs-migration" { "Yellow" }
            "migrated"       { "Cyan" }
            "pr-sent"        { "Blue" }
            default          { "White" }
        }
        Write-Host "  $($info.full_name)" -ForegroundColor White -NoNewline
        Write-Host "  [$($info.status)]" -ForegroundColor $statusColor

        # Check for changed files
        if (Test-Path $info.path) {
            Push-Location $info.path
            $changed = git diff --name-only HEAD 2>$null
            if ($changed) {
                Write-Host "    Changed: $($changed.Count) file(s)" -ForegroundColor DarkGray
            }
            Pop-Location
        }
    }
    Write-Host ""
    return 0
}

function Invoke-SendPRs {
    param([string[]]$Args)
    $params = Parse-NamedArgs $Args
    $workDir = $params["WorkDir"] ?? ".\bulk-migrations"
    $reposFilter = $params["Repos"]
    $yes = $params.ContainsKey("Yes")

    $manifestPath = Join-Path $workDir "manifest.json"
    if (-not (Test-Path $manifestPath)) {
        Write-Error "No manifest found at $manifestPath. Run 'prepare' first."
        return 1
    }

    $manifest = Get-Content $manifestPath | ConvertFrom-Json -AsHashtable

    # Filter to repos with changes
    $candidates = @()
    foreach ($repo in $manifest.Keys) {
        $info = $manifest[$repo]
        if ($info.status -eq "pr-sent") { continue }
        if ($reposFilter) {
            $filterList = $reposFilter -split ','
            if ($repo -notin $filterList) { continue }
        }
        if (Test-Path $info.path) {
            Push-Location $info.path
            $changed = git diff --name-only HEAD 2>$null
            Pop-Location
            if ($changed) {
                $candidates += @{ repo = $repo; info = $info; changed = $changed }
            }
        }
    }

    if ($candidates.Count -eq 0) {
        Write-Host "No repos ready for PRs." -ForegroundColor Yellow
        return 0
    }

    Write-Host "$($candidates.Count) repo(s) ready for PRs:" -ForegroundColor Cyan
    foreach ($c in $candidates) {
        Write-Host "  $($c.info.full_name) ($($c.changed.Count) files)" -ForegroundColor White
    }

    if (-not $yes) {
        $answer = Read-Host "Send PRs? [y/N]"
        if ($answer -notin @("y", "yes")) {
            Write-Host "Aborted."
            return 0
        }
    }

    $sent = 0
    foreach ($c in $candidates) {
        $repoDir = $c.info.path
        $repoFull = $c.info.full_name

        Write-Host "--- $repoFull ---" -ForegroundColor White

        Push-Location $repoDir
        try {
            git add -A
            git commit -m "Migrate from Chat Completions to Responses API (.NET)"
            git push origin $BranchName

            gh pr create --title $PrTitle --body $PrBody --base main --head $BranchName
            $sent++

            $manifest[$c.repo].status = "pr-sent"
        }
        catch {
            Write-Host "  Failed: $_" -ForegroundColor Red
        }
        finally {
            Pop-Location
        }
    }

    # Update manifest
    $manifest | ConvertTo-Json -Depth 3 | Set-Content $manifestPath
    Write-Host ""
    Write-Host "Sent $sent PR(s)." -ForegroundColor Green
    return 0
}

# Dispatch
$exitCode = switch ($SubCommand) {
    "prepare"  { Invoke-Prepare -Args $Arguments }
    "status"   { Invoke-Status -Args $Arguments }
    "send-prs" { Invoke-SendPRs -Args $Arguments }
}

exit $exitCode
